In [2]:
import numpy as np

In [98]:
import numpy as np
A = np.array([1,2,3])
print(A)

[1 2 3]


In [5]:
A

array([1, 2, 3])

In [10]:
len(A)

3

In [11]:
type(A[0])

numpy.int32

In [7]:
import numpy as np

A = [1,2,3]
B = [-1,-2,-3]
C = []

for a,b in zip (A,B):
    C.append(a+b)

print(C)

[0, 0, 0]


In [9]:
import numpy as np

A = np.array([1,2,3])
B = np.array([-1,-2,-3])
C = A+B #vectorization

print(C)

[0 0 0]


In [12]:
import numpy as numpy

a= np.array([0.1,0.2,0.3])
print(a)
print(a.dtype)
print(type(a[0]))

[0.1 0.2 0.3]
float64
<class 'numpy.float64'>


In [13]:
import numpy as numpy

a= np.array([1,2,3])
print(a)
print(a.dtype)
print(type(a[0]))

[1 2 3]
int32
<class 'numpy.int32'>


In [14]:
c = np.array([1,2,3], dtype=np.float64)

In [16]:
print(c)
print(c.dtype)

[1. 2. 3.]
float64


In [ ]:
c = np.array([1.,2.,3.])

In [17]:
print(c)
print(c.dtype)

[1. 2. 3.]
float64


In [18]:
d= np.array([1.1,2.2,3.3,4.7])
print(d.dtype)

float64


In [20]:
e = d.astype(np.int32)
print(e.dtype)

int32


In [21]:
print (e)

[1 2 3 4]


In [22]:
A = np.array([[1,2,3],[4,5,6]])
print(A)
print(type(A))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [23]:
A = np.array([[1,2,3],[4,5,6]])
print(A.ndim)

2


In [27]:
B = np.array([1,2,3])
print(B.ndim)
print(B.shape)

1
(3,)


In [28]:
C = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(C.ndim)
print(C.shape)

3
(2, 2, 3)


In [26]:
A = np.array([[1,2,3],[4,5,6]])
print(A.ndim)
print(A.shape)

2
(2, 3)


In [34]:
A = np.array([1,2,3])
print(A.ndim)
print(A.shape)
print(A.size)

1
(3,)
3


In [33]:
B = np.array([[1,2,3],[4,5,6]])
print(B.ndim)
print(B.shape)
print(B.size)

2
(2, 3)
6


In [32]:
C = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(C.ndim)
print(C.shape)
print

3
(2, 2, 3)
12


In [36]:
A = np.array([1,2,3])
print(A.dtype)
print(A.itemsize)
print(A.data)

int32
4


In [48]:
B = np.array([[1,2,3],[4,5,6]])
print(B.dtype)
print(B.itemsize)
print(B.data)

int32
4


In [49]:
C = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(C.dtype)
print(C.itemsize)
print(C.data)

int32
4


In [39]:
b = np.array([1,2,3,4,5,6])
print(b.max(), end= " ")
print(b.min(), end= " ")
print(b.sum(), end= " ")
print(b.mean(), end= " ")

6 1 21 3.5

In [45]:
c = np.array([[1,2,3],[4,5,6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
c.sum(axis =0) # 열방향으로 계산

array([5, 7, 9])

In [47]:
c.sum(axis =1)  #행방향으로 계산

array([ 6, 15])

In [ ]:
!conda install -c conda-forge opencv

In [1]:
import cv2
print(cv2.__version__)

4.0.1


In [3]:
import cv2

image = cv2.imread("image/airplane.jpg", cv2.IMREAD_COLOR)
cv2.imshow("airplane", image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [4]:
print(image.ndim)

3


In [8]:
import cv2
image_gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
cv2.imshow("Gray", image_gray)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [101]:
print(image_gray.ndim)
print(image_gray.itemsize)

2
1


In [14]:
import numpy as np

A = np.array([1,2,3])
A

array([1, 2, 3])

In [16]:
print(A.shape)

(3,)


In [18]:
B = np.array([[1,2,3],[4,5,6]])
print(B)

[[1 2 3]
 [4 5 6]]


In [20]:
B[1]

array([4, 5, 6])

In [22]:
print(B[0,2])

3


In [102]:
import numpy as np

C=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(C[1,0,2])

9


In [103]:
print(C[1,0,2])

9


In [104]:
import numpy as np

C= np.arange(24).reshape(2,3,4)
print(C)
print(C.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)


In [108]:
print(np.arange(10000).reshape(100,100))

1 6132 6133 6134 6135 6136 6137 6138 6139 6140 6141
  6142 6143 6144 6145 6146 6147 6148 6149 6150 6151 6152 6153 6154 6155
  6156 6157 6158 6159 6160 6161 6162 6163 6164 6165 6166 6167 6168 6169
  6170 6171 6172 6173 6174 6175 6176 6177 6178 6179 6180 6181 6182 6183
  6184 6185 6186 6187 6188 6189 6190 6191 6192 6193 6194 6195 6196 6197
  6198 6199]
 [6200 6201 6202 6203 6204 6205 6206 6207 6208 6209 6210 6211 6212 6213
  6214 6215 6216 6217 6218 6219 6220 6221 6222 6223 6224 6225 6226 6227
  6228 6229 6230 6231 6232 6233 6234 6235 6236 6237 6238 6239 6240 6241
  6242 6243 6244 6245 6246 6247 6248 6249 6250 6251 6252 6253 6254 6255
  6256 6257 6258 6259 6260 6261 6262 6263 6264 6265 6266 6267 6268 6269
  6270 6271 6272 6273 6274 6275 6276 6277 6278 6279 6280 6281 6282 6283
  6284 6285 6286 6287 6288 6289 6290 6291 6292 6293 6294 6295 6296 6297
  6298 6299]
 [6300 6301 6302 6303 6304 6305 6306 6307 6308 6309 6310 6311 6312 6313
  6314 6315 6316 6317 6318 6319 6320 6321 6322 6323 6324 6

In [110]:
# 다 출력하고 싶을때
import sys
np.set_printoptions(threshold=sys.maxsize)

In [39]:
import timeit
timeit.timeit('B**2', setup ='import numpy as np; B=np.arange(100)')

0.5174270999996224

In [40]:
import timeit
timeit.timeit('[i**2 for i in A]', setup='A=range(100)')

16.878802799999903

In [ ]:
##########################

In [42]:
#차원 맞추기
import numpy as np
a = np.array([1,2,3,4])
print(a.shape)

(4,)


In [45]:
## 설정에 따라서 1차원
a.shape = 1,4
print(a)

[[1 2 3 4]]


In [47]:
## 그리고 2차원... 설정을 어떻게 할지 주의해야 한다.
a.shape = 4,1
print(a)

[[1]
 [2]
 [3]
 [4]]


In [ ]:
#############배열 생성 및 shape변환

In [117]:
import numpy as np
A = np.zeros([2,3],dtype='uint8')
print(A)
print(A.dtype)

[[0 0 0]
 [0 0 0]]
uint8


In [51]:
import numpy as np

In [118]:
import numpy as np
A = np.ones((2,3),dtype='uint8')
print(A)
print(A.dtype)

[[1 1 1]
 [1 1 1]]
uint8


In [ ]:
##### np.empty()

In [55]:
C= np.empty((5,5))
print(C)
print()
print(C.dtype)

[[6.23042070e-307 4.67296746e-307 1.69121096e-306 8.34441742e-308
  1.37961302e-306]
 [9.34593493e-307 1.33511290e-306 1.33511969e-306 1.69120416e-306
  1.78022342e-306]
 [8.34449382e-308 1.06811422e-306 1.00132143e-307 8.34423068e-308
  8.90071135e-308]
 [1.11257937e-307 1.78022342e-306 2.44776798e-307 1.69119330e-306
  1.69122046e-306]
 [1.86921958e-306 6.89804133e-307 1.11261162e-306 8.34443015e-308
  2.22813476e-312]]

float64


In [ ]:
### np.random.random : 0~1 사이의 실수를 랜덤으로 생성

In [56]:
import random
import numpy as np
D=np.random.random((3,3))
print(D)

[[0.57967476 0.33222325 0.61444774]
 [0.10345675 0.79097968 0.72495691]
 [0.75954414 0.12766679 0.97815276]]


In [ ]:
###np.random.randint(시작, 끝,(가로, 세로))
# 시작~끝 사이의 정수를 랜덤으로 생성

In [99]:
import random
import numpy as np

E = np.random.randint(1,10,(3,5))
print(E)

[[9 4 6 6 2]
 [9 4 7 9 1]
 [8 4 1 8 2]]


In [ ]:
##연속 원소 배열 생성 함수
#np.arange(시작, 마지막,간격)
#np.arange(시작,마지막)
#np.arange(마지막)

In [ ]:
# 0<= x <50 범위에서 5간격으로 숫자를 뽑아 배열 생성
A = np.arange(0,50,5)
print(A)
# 0.1~2.5 사이에서 1간격으로 숫자를 뽑아 배열 생성
B= np.arange(0.1,2.5,1)
print(B)
#0<= x <10 내에서 배열 생성
C.np.arange(0,10)
print(C)

In [ ]:
#np.linspace()
-지정한 범위 내에서
-np.linspace(시작값, 마지막값, 샘플 갯수)
-np.linspace(시작값, 마지막값)

In [59]:
A = np.linspace(0,10,10)
print(A)

[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]


In [ ]:
#샘플 개수를 정하지 않으면 기본값은 50임
B = np

In [60]:
#0~15까지 16개 1차원 배열

A = np.arange(16)

B = A.reshape(4,4)

print(A)
print(B)
print(B.shape)
print(B.base)
print(B.base is A) # B가 배열 A의 데이터가 저장된 공간을 공유함.

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
(4, 4)
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
True


In [61]:
B[0] = -1 #한 행 전체를 -1로 바꾼다.
print(A)
print(B)

[-1 -1 -1 -1  4  5  6  7  8  9 10 11 12 13 14 15]
[[-1 -1 -1 -1]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [64]:
C = B.reshape(2,8).copy()
C[0] = 0
print(C)
print(B)

[[ 0  0  0  0  0  0  0  0]
 [ 8  9 10 11 12 13 14 15]]
[[-1 -1 -1 -1]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [65]:
C=np.arange(16)
print(C)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [ ]:
##### "-1"은 2차원 이든 3차원이든 한번만 사용해야 한다.(주의)

In [66]:
D=C.reshape(8,-1)
print(D)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]


In [67]:
E = C.reshape(-1,8)
print(E)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]


In [ ]:
###### ravel()
# 주어진 배열을 1차원 배열로 변환하여 리턴

In [4]:
import numpy as np
A = np.array([[1,2],[3,4]])
print(A)

[[1 2]
 [3 4]]


In [5]:
B = A.ravel()
print(B)
print(B.shape)

[1 2 3 4]
(4,)


In [6]:
print(B.base is A)

True


In [7]:
B = A.ravel([[[1,2],[3,4]],[[1,2],[3,4]]])
print(B)
print(B.shape)

ValueError: Non-string object detected for the array ordering. Please pass in 'C', 'F', 'A', or 'K' instead

In [ ]:
### newaxis()
# 차원을 증가시킴

In [73]:
a = np.array([1,2,3])
a = a[:,np.newaxis]
print(a.shape)
print(a)

(3, 1)
[[1]
 [2]
 [3]]


In [74]:
a = np.array([1,2,3])
a = a[np.newaxis,:]
print(a.shape)
print(a)

(1, 3)
[[1 2 3]]


In [ ]:
### hstack/vstack
# 결합함수
# hstack :가로로 결합
# vstack : 세로로 결합

In [78]:
import numpy as np
A = np.array([[1,2],[3,4]])
B = np.array([[1,0],[0,1]])
print(A)
print(B)
c=np.hstack((A,B))
print(C)
D = np.vstack((A,B))
print(D)

[[1 2]
 [3 4]]
[[1 0]
 [0 1]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[1 2]
 [3 4]
 [1 0]
 [0 1]]


In [ ]:
### column_stack()
# 1차원 벡터를 2차원 벡터로 만듬

In [82]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])
D = np.column_stack((a,b,c))
print(D)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
###concatenate()
# - 지정한 방향으로 배열 결합
# - axis = 0 : 열방향
# - axis = 1 : 행방향

In [85]:
import numpy as np
A = np.array([[1,2],[3,4]])
B = np.array([[1,0],[0,1]])

C=np.concatenate((A,B), axis=0) #열방향
print(C)
print()
D=np.concatenate((A,B), axis=1) #행방향
print(D)

[[1 2]
 [3 4]
 [1 0]
 [0 1]]

[[1 2 1 0]
 [3 4 0 1]]


In [86]:
###hsplit / vsplit
#-가로 또는 세로로 자르기

In [87]:
B = np.arange(18).reshape(3,6)
print(B)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]


In [88]:
C=np.hsplit(B,3)
print(C)

[array([[ 0,  1],
       [ 6,  7],
       [12, 13]]), array([[ 2,  3],
       [ 8,  9],
       [14, 15]]), array([[ 4,  5],
       [10, 11],
       [16, 17]])]


In [92]:
b = np.hsplit(B, (2,4))
print(b)

[array([[ 0,  1],
       [ 6,  7],
       [12, 13]]), array([[ 2,  3],
       [ 8,  9],
       [14, 15]]), array([[ 4,  5],
       [10, 11],
       [16, 17]])]


In [93]:
B = np.arange(18).reshape(6,3)
print(B)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [94]:
C=np.vsplit(B,3)
print(C)

[array([[0, 1, 2],
       [3, 4, 5]]), array([[ 6,  7,  8],
       [ 9, 10, 11]]), array([[12, 13, 14],
       [15, 16, 17]])]


In [95]:
b = np.vsplit(B, (2,4))
print(b)

[array([[0, 1, 2],
       [3, 4, 5]]), array([[ 6,  7,  8],
       [ 9, 10, 11]]), array([[12, 13, 14],
       [15, 16, 17]])]


In [12]:
def say_name(kid):
    print(kid)
def show_kid(kid):
    return kid
say_name("몽룡")
print()
show_kid("춘향")
print(say_name("향단"))
print(show_kid("방자"))

몽룡

향단
None
방자
