In [4]:
import numpy as np
import pandas as pd

In [5]:
string_data = pd.Series(['aardvark', 'artichoke', np.nan, 'avocado'])
string_data

0     aardvark
1    artichoke
2          NaN
3      avocado
dtype: object

In [7]:
string_data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [8]:
string_data[0] = None
string_data.isnull()

0     True
1    False
2     True
3    False
dtype: bool

|인자|설명|
|:------:|:---|
|dropna|누락된 데이터가 있는 축(low,column)을 제외시킨다. 어느정도의 누락데이터까지 용인할것인지 지정 할 수 있다.|
|fillna|누락된 데이터를 대신할 값을 채우거나 **'ffill'**이나 'bfill'같은 보간 메서드를 적용한다.|
|isnull|누락되거나 NA인 값을 알려주는 불리언 값이 저장된 같은 형의 객체를 반환|
|notnull|isnull과 반대되는 메서드|

In [10]:
from numpy import nan as NA
data=pd.Series([1,NA,3.5,NA,7])
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [11]:
data[data.notnull()] #notnull이 아닌 것만 출력하라.

0    1.0
2    3.5
4    7.0
dtype: float64

In [12]:
data = pd.DataFrame([[1., 6.5, 3.], [1., NA, NA],
                     [NA, NA, NA], [NA, 6.5, 3.]])
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [14]:
# dropna() : NaN이 하나라도 있으면 삭제
cleaned = data.dropna()
cleaned

0    1    2
0  1.0  6.5  3.0

In [15]:
# how=all : 모두 NaN이면 삭제
cleaned = data.dropna(how="all")
cleaned

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [16]:
#4번 열을 추가하고 NA값으로 지정
data[4] = NA
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [18]:
cleaned = data.dropna(axis='columns', how="all") #또는 axis = 1
cleaned

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [54]:
df = pd.DataFrame(np.random.randn(7,3))
df

0         1         2
0  0.145112 -1.139363 -0.477018
1 -0.130882  1.893343  1.607293
2 -0.192885 -3.143451 -0.585898
3 -1.354455 -0.340469  0.684185
4  0.815572 -1.424593  0.424964
5  0.096307  0.141663 -0.373174
6 -1.275838 -0.450456  1.159165

In [55]:
#변경할 자료에 접근하기 위해서 iloc사용
df.iloc[:4,1] =NA
df.iloc[:2,2] =NA
df


0         1         2
0  0.145112       NaN       NaN
1 -0.130882       NaN       NaN
2 -0.192885       NaN -0.585898
3 -1.354455       NaN  0.684185
4  0.815572 -1.424593  0.424964
5  0.096307  0.141663 -0.373174
6 -1.275838 -0.450456  1.159165

In [57]:
#cleaned = df.dropna()
cleaned = df.dropna(thresh=2) #하나만 비어있는 것은 남아있고, 2개가 NA인것은 삭제
cleaned

0         1         2
2 -0.192885       NaN -0.585898
3 -1.354455       NaN  0.684185
4  0.815572 -1.424593  0.424964
5  0.096307  0.141663 -0.373174
6 -1.275838 -0.450456  1.159165

In [ ]:
# NaN을 0으로 채워보자

## 결측치 채우기

In [59]:
filled = df.fillna(0)
filled

0         1         2
0  0.145112  0.000000  0.000000
1 -0.130882  0.000000  0.000000
2 -0.192885  0.000000 -0.585898
3 -1.354455  0.000000  0.684185
4  0.815572 -1.424593  0.424964
5  0.096307  0.141663 -0.373174
6 -1.275838 -0.450456  1.159165

In [101]:
# column별로 다르게 입력하고 싶을 때
filled = df.fillna({1:0.9,2:-0})
filled

0         1         2
0 -1.907879  0.900000  0.000000
1  0.791514  0.900000  0.000000
2 -0.239785 -1.426007  0.000000
3 -0.758614 -0.969619  0.000000
4 -1.004309  0.259411 -0.531183
5 -0.511015 -2.460560 -0.341299

In [72]:
df.fillna(0,inplace=True) #위와 다르게 따로 변수를 지정해 주지 않아도, inplace가 업데이트 시킴.
df

0         1         2
0 -0.532262  0.000000  0.000000
1 -1.010287  0.000000  0.000000
2  0.758218  2.817663  0.000000
3  0.310825  1.348285  0.000000
4  1.412081  0.025035 -0.979599
5 -0.905030 -1.676919 -0.338753

In [76]:
df = pd.DataFrame(np.random.randn(6,3))
df.iloc[:2,1] =NA
df.iloc[:4,2] =NA
df

0         1         2
0 -1.907879       NaN       NaN
1  0.791514       NaN       NaN
2 -0.239785 -1.426007       NaN
3 -0.758614 -0.969619       NaN
4 -1.004309  0.259411 -0.531183
5 -0.511015 -2.460560 -0.341299

In [77]:
filled = df.fillna(method='ffill')
filled

0         1         2
0 -1.907879       NaN       NaN
1  0.791514       NaN       NaN
2 -0.239785 -1.426007       NaN
3 -0.758614 -0.969619       NaN
4 -1.004309  0.259411 -0.531183
5 -0.511015 -2.460560 -0.341299

In [75]:
filled = df.fillna(method='ffill', limit=2)
filled

0         1         2
0  1.034443       NaN       NaN
1  0.910637       NaN       NaN
2  0.947758 -0.816767       NaN
3  0.914216 -2.168157       NaN
4  1.740266  1.239539  0.324406
5 -1.194169  2.359461  0.960961

### df.fillna(value=, method='ffill',axis=0, inplace=False, limit=)
- value : 비어있는 값을 채울 스칼라 값이나 dictionary 형식의 객체
- method : 보간법(기본 ffill)
- axis : 값을 채워 넣을 축 (기본 axis=0)
- inplace : 복사본을 생성하지 않고 호출한 객체에 값을 반환, 기본값=False
- limit : 값을 앞 또는 뒤로 몇개까지 채울지 지정

## 데이터변형
### 데이터 중복 제거

In [79]:
data = pd.DataFrame({'k1': ['one', 'two'] * 3 + ['two'],
                     'k2': [1, 1, 2, 3, 3, 4, 4]})
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [80]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [81]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [83]:
data['v1'] = range(7)
data

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [84]:
data.drop_duplicates(['k1'])

k1  k2  v1
0  one   1   0
1  two   1   1

In [86]:
data.drop_duplicates(['k2'])

k1  k2  v1
0  one   1   0
2  one   2   2
3  two   3   3
5  two   4   5

In [ ]:
data.drop_duplicates(['k1','k2'], keep='last') #kepp='last' : 마지막만 남기고, 중복되는 나머지는 모두 삭제.

### 데이터 변형하기

In [87]:
data = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon',
                              'Pastrami', 'corned beef', 'Bacon',
                              'pastrami', 'honey ham', 'nova lox'],
                     'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [89]:
meat_to_animal = {
  'bacon': 'pig',
  'pulled pork': 'pig',
  'pastrami': 'cow',
  'corned beef': 'cow',
  'honey ham': 'pig',
  'nova lox': 'salmon'
}
meat_to_animal

{'bacon': 'pig',
 'pulled pork': 'pig',
 'pastrami': 'cow',
 'corned beef': 'cow',
 'honey ham': 'pig',
 'nova lox': 'salmon'}

In [90]:
lower_cased = data['food'].str.lower()
lower_cased

0          bacon
1    pulled pork
2          bacon
3       pastrami
4    corned beef
5          bacon
6       pastrami
7      honey ham
8       nova lox
Name: food, dtype: object

In [91]:
data['animal']= lower_cased.map(meat_to_animal)
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

### 람다식으로 똑같이 표현

In [92]:
data['food'].map(lambda x :meat_to_animal[x.lower()])

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

In [93]:
# lower_cased = data['food'].str.lower()
# data['animal']= lower_cased.map(meat_to_animal)

data['animal']= data['food'].map(lambda x :meat_to_animal[x.lower()])
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [94]:
data = pd.Series([1.,-999.,2,-1000])

In [97]:
data2 = data.replace([-999,-1000], np.nan)
data2

0       1.0
1       NaN
2       2.0
3   -1000.0
dtype: float64

In [ ]:
data

In [98]:
data2 = data.replace([-999,-1000], [np.nan,0])
data2

0    1.0
1    NaN
2    2.0
3    0.0
dtype: float64

In [99]:
data2 = data.replace({-999: np.nan, -1000:0})
#-999 -> Nan, -1000 -> 0
data2

0    1.0
1    NaN
2    2.0
3    0.0
dtype: float64

#### Index 인덱스 변경

In [104]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
                    index=['Ohio', 'Colorado', 'New York'],
                    columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [106]:
#인덱스 변경
transform = lambda x: x[:4].upper() #4자리까지만 표시하고 대문자로 바꿔라.
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [107]:
data.index = data.index.map(transform)
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [108]:
####

In [109]:
data.rename(index=str.title, columns=str.upper)

ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

### 일부만 변경

In [110]:
data.rename(index={'OHIO':'INDIANA'}, columns={'three':'peekaboo'})
# 출력이 되어 있지만, 값이 변경되어 있는 것은 아니다. 

one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

In [112]:
# inplace로 인해서 값이 업데이트 되었다.
data.rename(index={'OHIO':'INDIANA'}, inplace=True)
data

one  two  three  four
INDIANA    0    1      2     3
COLO       4    5      6     7
NEW        8    9     10    11

#### 조건에 따라 자료 분류하기

In [116]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [117]:
#18~25
#26~35
#35~60
#60이상

bins = [18,25,35,60,100]
cats = pd.cut(ages,bins)
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [118]:
#0~3가지의 값으로 변경
cats.codes #값이 몇번째 그룹에 속하는지 표시

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [119]:
cats.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]],
              closed='right',
              dtype='interval[int64]')

In [120]:
pd.value_counts(cats)

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

In [123]:
#왼쪽은 포함/ 오른쪽은 포함안됨
pd.cut(ages,[18,26,36,61,100], right=False)

[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [26, 36), [61, 100), [36, 61), [36, 61), [26, 36)]
Length: 12
Categories (4, interval[int64]): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [129]:
group_names = ['Youth','YoungAdult','MiddleAged','Senior']

In [130]:
pd.cut(ages,bins,labels=group_names)

[Youth, Youth, Youth, YoungAdult, Youth, ..., YoungAdult, Senior, MiddleAged, MiddleAged, YoungAdult]
Length: 12
Categories (4, object): [Youth < YoungAdult < MiddleAged < Senior]

In [136]:
data = np.random.rand(20)
data

array([0.30938705, 0.60218726, 0.53846283, 0.23262917, 0.79361614,
       0.73222786, 0.41873487, 0.10544123, 0.76361293, 0.54102772,
       0.66279997, 0.32415421, 0.09262174, 0.50063807, 0.77434613,
       0.47404345, 0.32296961, 0.85806176, 0.10240086, 0.50544952])

In [137]:
pd.cut(data,4,precision=2)

[(0.28, 0.48], (0.48, 0.67], (0.48, 0.67], (0.092, 0.28], (0.67, 0.86], ..., (0.28, 0.48], (0.28, 0.48], (0.67, 0.86], (0.092, 0.28], (0.48, 0.67]]
Length: 20
Categories (4, interval[float64]): [(0.092, 0.28] < (0.28, 0.48] < (0.48, 0.67] < (0.67, 0.86]]

In [148]:
data = pd.DataFrame(np.random.randn(1000,4))
data

0         1         2         3
0    0.768220 -0.216388 -0.123575  1.521370
1    0.830080  0.062651 -0.002764  0.182169
2    2.377143  0.588035 -0.772004  0.684952
3   -1.894328 -0.080078  1.649274  0.216342
4    0.288786  1.162128 -0.228602 -1.018986
..        ...       ...       ...       ...
995 -1.399102 -0.121045  0.181248  1.139444
996  1.790937  0.066468 -0.469748  0.747149
997 -1.170640 -0.361449 -0.616333  1.578760
998 -0.276530 -0.120698 -1.256778  1.500841
999  2.166098 -1.863460  0.153872 -0.122434

[1000 rows x 4 columns]

In [149]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.020248     0.003600    -0.054770     0.005558
std       0.992086     1.005640     0.967825     1.043703
min      -2.965715    -4.138633    -3.324975    -3.756288
25%      -0.697508    -0.689503    -0.710189    -0.680579
50%      -0.040224    -0.005639    -0.098296     0.019071
75%       0.666344     0.697515     0.572986     0.695787
max       3.440228     3.454565     2.988530     3.176520

In [150]:
col = data[2]
col[np.abs(col)>3]

694   -3.324975
Name: 2, dtype: float64

In [151]:
data[(np.abs(data)>3).any(1)] #데이터가 3보다 큰것이 하나라도 있으면 출력하라.

0         1         2         3
44  -1.267442  3.183366  0.122332 -0.056532
62   3.324194 -0.690054 -0.623503 -1.972684
110 -0.266188 -3.308783  1.281327  0.320404
193  0.964081  0.479459  0.477314 -3.004774
253 -2.082104 -4.138633 -1.700588 -0.462470
257  1.774246 -0.285136  0.541739  3.176520
443  0.376640  1.014566 -0.607893  3.092477
572 -1.157912 -0.036498 -0.512870 -3.756288
694  0.395262  0.206371 -3.324975  0.761835
900  3.440228  0.146970  2.988530  0.838890
917 -0.044835  3.454565 -1.893941  0.122215

In [154]:
data[np.abs(data)>3] = np.sign(data)*3
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.021013     0.004409    -0.054445     0.006050
std       0.989602     0.998573     0.966780     1.040438
min      -2.965715    -3.000000    -3.000000    -3.000000
25%      -0.697508    -0.689503    -0.710189    -0.680579
50%      -0.040224    -0.005639    -0.098296     0.019071
75%       0.666344     0.697515     0.572986     0.695787
max       3.000000     3.000000     2.988530     3.000000

In [155]:
np.sign(data).head()

0    1    2    3
0  1.0 -1.0 -1.0  1.0
1  1.0  1.0 -1.0  1.0
2  1.0  1.0 -1.0  1.0
3 -1.0 -1.0  1.0  1.0
4  1.0  1.0 -1.0 -1.0

In [156]:
data.head()

0         1         2         3
0  0.768220 -0.216388 -0.123575  1.521370
1  0.830080  0.062651 -0.002764  0.182169
2  2.377143  0.588035 -0.772004  0.684952
3 -1.894328 -0.080078  1.649274  0.216342
4  0.288786  1.162128 -0.228602 -1.018986

In [ ]:
###

In [158]:
df = pd.DataFrame(np.arange(5 * 4).reshape((5, 4)))
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [159]:
sampler = np.random.permutation(5)
sampler

array([4, 2, 1, 0, 3])

In [162]:
df.take(sampler)

0   1   2   3
4  16  17  18  19
2   8   9  10  11
1   4   5   6   7
0   0   1   2   3
3  12  13  14  15

In [161]:
df.sample(n=3)

0   1   2   3
4  16  17  18  19
3  12  13  14  15
2   8   9  10  11

In [163]:
choices = pd.Series([5, 7, -1, 6, 4])
draws = choices.sample(n=10, replace=True)
draws

3    6
0    5
4    4
4    4
3    6
1    7
0    5
3    6
4    4
3    6
dtype: int64

In [164]:
df = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'],
                   'data1': range(6)})
df

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

### 원 핫 인코딩 one-hot incoding


In [166]:
pd.get_dummies(df['key'])

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [173]:
dummies = pd.get_dummies(df['key'], prefix='key')
dummies

key_a  key_b  key_c
0      0      1      0
1      0      1      0
2      1      0      0
3      0      0      1
4      1      0      0
5      0      1      0

In [174]:
df_with_dummy = df[['data1']].join(dummies)
df_with_dummy

data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

In [175]:
mnames = ['movie_id', 'title', 'genres']
movies = pd.read_table('data/movies.dat', sep='::', header=None, names=mnames)
movies[:10]

movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

In [176]:
all_genres = []
for x in movies.genres:
    all_genres.extend(x.split('|'))
genres = pd.unique(all_genres)
genres

array(['Animation', "Children's", 'Comedy', 'Adventure', 'Fantasy',
       'Romance', 'Drama', 'Action', 'Crime', 'Thriller', 'Horror',
       'Sci-Fi', 'Documentary', 'War', 'Musical', 'Mystery', 'Film-Noir',
       'Western'], dtype=object)

In [178]:
zero_matrix = np.zeros((len(movies),len(genres)))
dummies = pd.DataFrame(zero_matrix, columns=genres)
dummies

Animation  Children's  Comedy  Adventure  Fantasy  Romance  Drama  \
0           0.0         0.0     0.0        0.0      0.0      0.0    0.0   
1           0.0         0.0     0.0        0.0      0.0      0.0    0.0   
2           0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3           0.0         0.0     0.0        0.0      0.0      0.0    0.0   
4           0.0         0.0     0.0        0.0      0.0      0.0    0.0   
...         ...         ...     ...        ...      ...      ...    ...   
3878        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3879        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3880        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3881        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3882        0.0         0.0     0.0        0.0      0.0      0.0    0.0   

      Action  Crime  Thriller  Horror  Sci-Fi  Documentary  War  Musical  \
0        0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
1        0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
2        0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
3        0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
4        0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
...      ...    ...       ...     ...     ...          ...  ...      ...   
3878     0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
3879     0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
3880     0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
3881     0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
3882     0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   

      Mystery  Film-Noir  Western  
0         0.0        0.0      0.0  
1         0.0        0.0      0.0  
2         0.0        0.0      0.0  
3         0.0        0.0      0.0  
4         0.0        0.0      0.0  
...       ...        ...      ...  
3878      0.0        0.0      0.0  
3879      0.0        0.0      0.0  
3880      0.0        0.0      0.0  
3881      0.0        0.0      0.0  
3882      0.0        0.0      0.0  

[3883 rows x 18 columns]

In [181]:
gen = movies.genres[0]
gen.split('|')
dummies.columns.get_indexer(gen.split('|'))

array([0, 1, 2], dtype=int64)

In [183]:
for i, gen in enumerate(movies.genres):
    indices = dummies.columns.get_indexer(gen.split('|'))
    dummies.iloc[i, indices] = 1

dummies

Animation  Children's  Comedy  Adventure  Fantasy  Romance  Drama  \
0           1.0         1.0     1.0        0.0      0.0      0.0    0.0   
1           0.0         1.0     0.0        1.0      1.0      0.0    0.0   
2           0.0         0.0     1.0        0.0      0.0      1.0    0.0   
3           0.0         0.0     1.0        0.0      0.0      0.0    1.0   
4           0.0         0.0     1.0        0.0      0.0      0.0    0.0   
...         ...         ...     ...        ...      ...      ...    ...   
3878        0.0         0.0     1.0        0.0      0.0      0.0    0.0   
3879        0.0         0.0     0.0        0.0      0.0      0.0    1.0   
3880        0.0         0.0     0.0        0.0      0.0      0.0    1.0   
3881        0.0         0.0     0.0        0.0      0.0      0.0    1.0   
3882        0.0         0.0     0.0        0.0      0.0      0.0    1.0   

      Action  Crime  Thriller  Horror  Sci-Fi  Documentary  War  Musical  \
0        0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
1        0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
2        0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
3        0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
4        0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
...      ...    ...       ...     ...     ...          ...  ...      ...   
3878     0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
3879     0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
3880     0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
3881     0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
3882     0.0    0.0       1.0     0.0     0.0          0.0  0.0      0.0   

      Mystery  Film-Noir  Western  
0         0.0        0.0      0.0  
1         0.0        0.0      0.0  
2         0.0        0.0      0.0  
3         0.0        0.0      0.0  
4         0.0        0.0      0.0  
...       ...        ...      ...  
3878      0.0        0.0      0.0  
3879      0.0        0.0      0.0  
3880      0.0        0.0      0.0  
3881      0.0        0.0      0.0  
3882      0.0        0.0      0.0  

[3883 rows x 18 columns]

In [195]:
pd.set_option('display.max_columns',25)
# pd.set_option('display.max_rows',300)
movies_windic = movies.join(dummies.add_prefix('Genre_'))
movies_windic.iloc[0]
movies_windic.head(3)

movie_id                    title                        genres  \
0         1         Toy Story (1995)   Animation|Children's|Comedy   
1         2           Jumanji (1995)  Adventure|Children's|Fantasy   
2         3  Grumpier Old Men (1995)                Comedy|Romance   

   Genre_Animation  Genre_Children's  Genre_Comedy  Genre_Adventure  \
0              1.0               1.0           1.0              0.0   
1              0.0               1.0           0.0              1.0   
2              0.0               0.0           1.0              0.0   

   Genre_Fantasy  Genre_Romance  Genre_Drama  Genre_Action  Genre_Crime  \
0            0.0            0.0          0.0           0.0          0.0   
1            1.0            0.0          0.0           0.0          0.0   
2            0.0            1.0          0.0           0.0          0.0   

   Genre_Thriller  Genre_Horror  Genre_Sci-Fi  Genre_Documentary  Genre_War  \
0             0.0           0.0           0.0                0.0        0.0   
1             0.0           0.0           0.0                0.0        0.0   
2             0.0           0.0           0.0                0.0        0.0   

   Genre_Musical  Genre_Mystery  Genre_Film-Noir  Genre_Western  
0            0.0            0.0              0.0            0.0  
1            0.0            0.0              0.0            0.0  
2            0.0            0.0              0.0            0.0

In [196]:
np.random.seed(12345)
values = np.random.rand(10)
values

array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503,
       0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987])

In [197]:
bins = [0,0.2,0.4,0.6,0.8,1]
pd.get_dummies(pd.cut(values,bins))

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           0           0           0           0           1
1           0           1           0           0           0
2           1           0           0           0           0
3           0           1           0           0           0
4           0           0           1           0           0
5           0           0           1           0           0
6           0           0           0           0           1
7           0           0           0           1           0
8           0           0           0           1           0
9           0           0           0           1           0

In [200]:
val = 'a,b, guido'
val.split(',')

['a', 'b', ' guido']

In [202]:
# split할때 공백을 자동으로 없애 줌
pieces = [x.strip() for x in val.split(',')]
pieces

['a', 'b', 'guido']

In [204]:
first, second, third = pieces
first + '::'+second + '::' + third

'a::b::guido'

In [206]:
'::'.join(pieces)

'a::b::guido'

In [207]:
'guido' in val

True

In [209]:
val.index(',')

1

In [210]:
val.index(':')

ValueError: substring not found

In [211]:
val.count(",")

2

In [212]:
val.replace(',', '::')

'a::b:: guido'

In [213]:
val.replace(',','')

'ab guido'