In [ ]:
############Indexing

In [11]:
import numpy as np
A = np.arange(0,15,2)
print(A)

[ 0  2  4  6  8 10 12 14]


In [6]:
print(A.shape)
for i in range(A.size):
    print(A[i],end=" ")

(8,)
0 2 4 6 8 10 12 14

In [7]:
print(A.shape)
for i in range(A.size):
    print("A[{}] : {}".format(i,A[i]))

(8,)
A[0] : 0
A[1] : 2
A[2] : 4
A[3] : 6
A[4] : 8
A[5] : 10
A[6] : 12
A[7] : 14


In [10]:
for i in range(A.size):
    n= -(i+1)
    print("A[{}] : {}".format(n,A[n]))

A[-1] : 14
A[-2] : 12
A[-3] : 10
A[-4] : 8
A[-5] : 6
A[-6] : 4
A[-7] : 2
A[-8] : 0


In [73]:
import numpy as np
A = np.arange(12).reshape(3,4)
print(A)
print("A.ndim :", A.ndim)
print(A.shape, A.shape[0],A.shape[1])
for i in range(A.shape[0]):
    for j in range(A.shape[1]):
        print("A[{0}][{1}] : {2}".format(i,j,A[i][j]))
    print()
    
print()
for i in range(A.shape[0]):
    print("A[{}]:{}".format(i,A[i]))


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
A.ndim : 2
(3, 4) 3 4
A[0][0] : 0
A[0][1] : 1
A[0][2] : 2
A[0][3] : 3

A[1][0] : 4
A[1][1] : 5
A[1][2] : 6
A[1][3] : 7

A[2][0] : 8
A[2][1] : 9
A[2][2] : 10
A[2][3] : 11


A[0]:[0 1 2 3]
A[1]:[4 5 6 7]
A[2]:[ 8  9 10 11]


In [30]:
import numpy as np

A= np.arange(9).reshape(3,3)
print(A)

print()
print()
for row in A: #A => [[1,2,3],[4,5,6],[7,8,9]]
    print(row)
print()

#행렬 전치
print(A.T)
print()
for column in A.T:
    print(column)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


[0 1 2]
[3 4 5]
[6 7 8]

[[0 3 6]
 [1 4 7]
 [2 5 8]]

[0 3 6]
[1 4 7]
[2 5 8]


In [33]:
import numpy as np
A = np.arange(9).reshape(3,3)
print(A)
print()
for a in A.flat:
    print(a, end=" ")

[[0 1 2]
 [3 4 5]
 [6 7 8]]

0 1 2 3 4 5 6 7 8

In [35]:
import numpy as np
A = np.arange(0,20,2) #1차원 행렬
print(A)

[ 0  2  4  6  8 10 12 14 16 18]


In [39]:
print(A[0:3])
print(A[:3]) #0에서 시작하면 생략가능

[0 2 4]
[0 2 4]


In [41]:
print(A[7:10])
print(A[7:]) # 끝 인덱스 생략가능

[14 16 18]
[14 16 18]


In [42]:
print(A[:]) #전체 원소
print(A[::2]) # 첫번째 원소부터 2씩 건너뜀

[ 0  2  4  6  8 10 12 14 16 18]
[ 0  4  8 12 16]


In [46]:
print(A[:-2]) # 마지막 2개 원소 제외
print(A[-100000:-2])

[ 0  2  4  6  8 10 12 14]
[ 0  2  4  6  8 10 12 14]


In [ ]:
print(A[-2:]) #마지막 2개 원소만 취함

In [44]:
print(A[0:3].shape)
print(A[0:3].ndim)

(3,)
1


In [48]:
print(A)
A[0:3] = 100
print(A)

[ 0  2  4  6  8 10 12 14 16 18]
[100 100 100   6   8  10  12  14  16  18]


In [66]:
import numpy as np
A = np.arange(1,13).reshape(3,4)
print(A)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [67]:
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
######## 각 원소에 접근
A[row][col] or A[row,col]

In [72]:
for i in range(A.shape[0]):
    for j in range(A.shape[1]):
        print("A[{0}][{1}] : {2:2d} or A[{3},{4}] : {5:2d}".format(i,j,A[i][j],i,j,A[i,j]))

A[0][0] :  2 or A[0,0] :  2
A[0][1] :  4 or A[0,1] :  4
A[1][0] :  6 or A[1,0] :  6
A[1][1] :  8 or A[1,1] :  8


In [ ]:
#### 행의 슬라이싱  
#####A[i] or A[i,:]

In [56]:
for i in range(A.shape[0]):
    print("A[{0}] : {1} or A[{2},:] : {3}".format(i,A[i],i,A[i,:]))

A[0] : [1 2 3 4] or A[0,:] : [1 2 3 4]
A[1] : [5 6 7 8] or A[1,:] : [5 6 7 8]
A[2] : [ 9 10 11 12] or A[2,:] : [ 9 10 11 12]


In [68]:
print(A[:2,:2])


[[1 2]
 [5 6]]


In [65]:
A[:2,:2] =0
print(A)

[[ 0  0  3  4]
 [ 0  0  7  8]
 [ 9 10 11 12]]


In [69]:
print(A[0]) #행 슬라이싱
print(A[:,1]) # 열 슬라이싱
#print(A[...,1]) #열 슬라이싱

[1 2 3 4]
[ 2  6 10]


In [71]:
import numpy as np
A = np.array([2,4,6,8]).reshape(2,2)
B = np.array([2,2,2,2]).reshape(2,2)
print(A)
print(B)

[[2 4]
 [6 8]]
[[2 2]
 [2 2]]
