In [2]:
import numpy as np
A = np.array([2,4,6,8]).reshape(2,2)
B = np.array([2,2,2,2]).reshape(2,2)
print(A)
print(B)

[[2 4]
 [6 8]]
[[2 2]
 [2 2]]


In [4]:
print(A+B)
print(A-B)
print(A*B)
print(A/B)


[[ 4  6]
 [ 8 10]]
[[0 2]
 [4 6]]
[[ 4  8]
 [12 16]]
[[1. 2.]
 [3. 4.]]


In [3]:
# 행렬의 곱셈
print(A@B) 

[[12 12]
 [28 28]]


In [6]:
print(np.dot(A,B))
print(A.dot(B))

[[12 12]
 [28 28]]
[[12 12]
 [28 28]]


In [ ]:
###broadcasting
# 다른 크기의 배열간의 산술연산

In [ ]:
A.shape = (2,3,4,5)
B.shape = (5,) 
#=>B의 차원의 개수가 같아지도록 B shape 왼쪽에 1추가
# B.shape = (1,1,1,5)
# 두 배열을 비교
# 대응하는 차원이 같거나 한쪽이 1인 경우에만 브로드캐스팅 가능

In [ ]:
# 브로드 캐스팅 가능?
A.shape : (2,1,3,1)
B.shape : (6,1,3) = (1,6,1,3) =>가능
=> B.shape :(1,6,1,3)

A.shape :(2,3,4)
B.shape :(3,1)=>(1,3,1) =>가능

A.shape :(3,)
B.shape :(4,) => 불가능

A.shape : (3,3,5)
B.shape :(3,1,5) =>가능

In [8]:
import numpy as np
A=np.arange(10,130,10).reshape(3,4)
print(A)
print(A.shape)
B=np.arange(1,5)
print(B)
print(B.shape)

[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]
(3, 4)
[1 2 3 4]
(4,)


In [9]:
A+B

array([[ 11,  22,  33,  44],
       [ 51,  62,  73,  84],
       [ 91, 102, 113, 124]])

In [16]:
import numpy as np
A = np.arange(10,130,10).reshape(3,4)
print(A)
B = np.array([0,5])
print(B.shape)

[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]
(2,)


In [17]:
B = shape(5,)
print(B)


NameError: name 'shape' is not defined

In [18]:
### vectorize

In [19]:
import numpy as np

matrix = np.arange(1,10).reshape(3,3)
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [21]:
add_100 = lambda i:i+100

In [23]:
vectorized_add_100 = np.vectorize(add_100)
vectorized_add_100(matrix)

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [30]:
find_odd = lambda i : i*(i%2)
find_even = lambda i : i if i%2==0 else 0

In [32]:
vectorized_find_odd = np.vectorize(find_odd)
vectorized_find_even = np.vectorize(find_even)
print(vectorized_find_odd(matrix))
print()
print(vectorized_find_even(matrix))

[[1 0 3]
 [0 5 0]
 [7 0 9]]

[[0 2 0]
 [4 0 6]
 [0 8 0]]


In [29]:
import numpy as np

matrix = np.arange(1,10).reshape(3,3)
print(matrix)

print(np.max(matrix))
print(np.min(matrix))
print(np.max(matrix, axis=1)) #각 행에서 최고값 찾음
print(np.min(matrix, axis=0)) #각 열에서 최소값 찾음

[[1 2 3]
 [4 5 6]
 [7 8 9]]
9
1
[3 6 9]
[1 2 3]


In [36]:
# keepdims 각 행마다의 최대값
vector_column = np.max(matrix, axis=1, keepdims=True)
print(vector_column)
print()
print(vector_column.shape)

[[3]
 [6]
 [9]]

(3, 1)


In [39]:
# (3,1)과 (3,3)비교후 브로드캐스팅이 가능하기 때문에 연산이 가능해짐.
print(matrix.shape)
print()
print(matrix - vector_column) 

(3, 3)

[[-2 -1  0]
 [-2 -1  0]
 [-2 -1  0]]


In [ ]:
####평균, 분산, 표준편차

In [40]:
import numpy as np

matrix = np.arange(1,10).reshape(3,3)
print(matrix)

print("평균 :",np.mean(matrix))
print("분산 :",np.var(matrix))
print("표준편차 :",np.std(matrix))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
평균 : 5.0
분산 : 6.666666666666667
표준편차 : 2.581988897471611


In [41]:
print("평균 :",np.mean(matrix))
print("평균 :", np.mean(matrix,axis=0))

평균 : 5.0
평균 : [4. 5. 6.]


In [42]:
print(np.std(matrix))
print(np.std(matrix,ddof=1))

2.581988897471611
2.7386127875258306


In [ ]:
##행렬의 전치(전치 행렬, trnaspose)

In [43]:
import numpy as np

matrix = np.arange(1,10).reshape(3,3)
print(matrix)
print()
print(matrix.T)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [44]:
np.array([1,2,3,4,5,6,7]).T

array([1, 2, 3, 4, 5, 6, 7])

In [45]:
np.array([[1,2,3,4,5,6,7]]).T

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])

In [46]:
import numpy as np

matrix = np.arange(1,10).reshape(3,3)
print(matrix)
print()
print(matrix.T)
print(matrix.transpose())

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [48]:
# matrix의 rank구하기

matrix = np.array([[1,1,1],[1,1,10],[1,1,15]])
print(matrix)
np.linalg.matrix_rank(matrix)

[[ 1  1  1]
 [ 1  1 10]
 [ 1  1 15]]


2

In [ ]:
## 역행렬 invers matrix

In [49]:
matrix = np.array([[1,4],[2,5]])
print(matrix)

[[1 4]
 [2 5]]


In [51]:
#역행렬
inv_matrix = np.linalg.inv(matrix)
print(inv_matrix)

[[-1.66666667  1.33333333]
 [ 0.66666667 -0.33333333]]


In [52]:
matrix @ inv_matrix

array([[1., 0.],
       [0., 1.]])

In [57]:
inv_matrix = np.linalg.pinv(matrix)
print(inv_matrix)

[[-0.94444444  0.44444444]
 [-0.11111111  0.11111111]
 [ 0.72222222 -0.22222222]]


In [54]:
matrix = np.arange(1,7).reshape(2,3)
print(matrix)

[[1 2 3]
 [4 5 6]]


In [58]:
matrix @ inv_matrix

array([[1.00000000e+00, 2.22044605e-16],
       [0.00000000e+00, 1.00000000e+00]])

In [59]:
print(np.round(matrix @ inv_matrix,0))

[[1. 0.]
 [0. 1.]]


In [60]:
#######

In [62]:
import random
a= np.arange(5)
print(a)
np.random.shuffle(a)
print(a)

[0 1 2 3 4]
[0 4 3 1 2]


In [63]:
import random
a = np.arange(5)
print(a)
b= np.random.permutation(a)
print(b)

[0 1 2 3 4]
[1 2 0 4 3]


In [64]:
print(np.random.permutation(5))

[0 4 3 2 1]
